import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/_styles/globals.css";
import AppHeader from "./_components/AppHeader";
import { ToastProvider } from "./_components/ToastContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative flex min-h-screen flex-col bg-skin-whisper text-skin-black antialiased`}
      >
        <AppHeader />
        <Toaster />

        <ToastProvider>
          <div className="grid flex-1 px-8 py-12">
            <main className="mx-auto w-full max-w-3xl">{children}</main>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
