export const testInvoices = [
  {
    invoiceId: "INV001",
    description: "Web development services",
    status: "pending",
    paymentDue: "2023-08-10T00:00:00Z",
    paymentTerms: "30 days",
    clientName: "Alice Johnson",
    clientEmail: "alice@example.com",
    total: 2500.0,
    items: [
      {
        name: "Website design",
        qty: 1,
        price: 1500.0,
        totalPrice: 1500.0,
        id: "item01",
      },
      {
        name: "SEO services",
        qty: 1,
        price: 1000.0,
        totalPrice: 1000.0,
        id: "item02",
      },
    ],
    senderAddress: {
      street: "123 Main St",
      city: "Metropolis",
      postCode: "12345",
      country: "USA",
    },
    clientAddress: {
      street: "456 Elm St",
      city: "Smalltown",
      postCode: "67890",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a02",
  },
  {
    invoiceId: "INV002",
    description: "Graphic design services",
    status: "paid",
    paymentDue: "2023-08-15T00:00:00Z",
    paymentTerms: "45 days",
    clientName: "Bob Smith",
    clientEmail: "bob@example.com",
    total: 800.0,
    items: [
      {
        name: "Logo design",
        qty: 1,
        price: 500.0,
        totalPrice: 500.0,
        id: "item03",
      },
      {
        name: "Brochure design",
        qty: 1,
        price: 300.0,
        totalPrice: 300.0,
        id: "item04",
      },
    ],
    senderAddress: {
      street: "789 Oak St",
      city: "Largetown",
      postCode: "98765",
      country: "USA",
    },
    clientAddress: {
      street: "321 Pine St",
      city: "Tinyville",
      postCode: "54321",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a04",
  },
  {
    invoiceId: "INV003",
    description: "Consulting services",
    status: "pending",
    paymentDue: "2023-09-01T00:00:00Z",
    paymentTerms: "15 days",
    clientName: "Charlie Brown",
    clientEmail: "charlie@example.com",
    total: 1200.0,
    items: [
      {
        name: "Business consultation",
        qty: 3,
        price: 400.0,
        totalPrice: 1200.0,
        id: "item05",
      },
    ],
    senderAddress: {
      street: "987 Maple St",
      city: "Middletown",
      postCode: "65432",
      country: "USA",
    },
    clientAddress: {
      street: "654 Cedar St",
      city: "Newville",
      postCode: "87654",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a06",
  },
  {
    invoiceId: "INV004",
    description: "Marketing services",
    status: "draft",
    paymentDue: "2023-07-20T00:00:00Z",
    paymentTerms: "7 days",
    clientName: "Diana Prince",
    clientEmail: "diana@example.com",
    total: 1500.0,
    items: [
      {
        name: "Social media marketing",
        qty: 1,
        price: 1500.0,
        totalPrice: 1500.0,
        id: "item06",
      },
    ],
    senderAddress: {
      street: "654 Birch St",
      city: "Oldtown",
      postCode: "13579",
      country: "USA",
    },
    clientAddress: {
      street: "321 Spruce St",
      city: "Newcity",
      postCode: "97531",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a08",
  },
  {
    invoiceId: "INV005",
    description: "IT support services",
    status: "pending",
    paymentDue: "2023-08-05T00:00:00Z",
    paymentTerms: "30 days",
    clientName: "Eve Adams",
    clientEmail: "eve@example.com",
    total: 500.0,
    items: [
      {
        name: "System maintenance",
        qty: 5,
        price: 100.0,
        totalPrice: 500.0,
        id: "item07",
      },
    ],
    senderAddress: {
      street: "123 Pine St",
      city: "Techville",
      postCode: "24680",
      country: "USA",
    },
    clientAddress: {
      street: "456 Maple St",
      city: "Gadgettown",
      postCode: "13579",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a10",
  },
  {
    invoiceId: "INV006",
    description: "Content writing services",
    status: "paid",
    paymentDue: "2023-08-01T00:00:00Z",
    paymentTerms: "60 days",
    clientName: "Fiona Green",
    clientEmail: "fiona@example.com",
    total: 700.0,
    items: [
      {
        name: "Blog articles",
        qty: 7,
        price: 100.0,
        totalPrice: 700.0,
        id: "item08",
      },
    ],
    senderAddress: {
      street: "111 River Rd",
      city: "Seaside",
      postCode: "24680",
      country: "USA",
    },
    clientAddress: {
      street: "222 Ocean Ave",
      city: "Beachville",
      postCode: "97531",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a12",
  },
  {
    invoiceId: "INV007",
    description: "Data analysis services",
    status: "draft",
    paymentDue: "2023-08-15T00:00:00Z",
    paymentTerms: "30 days",
    clientName: "George White",
    clientEmail: "george@example.com",
    total: 1800.0,
    items: [
      {
        name: "Data processing",
        qty: 3,
        price: 600.0,
        totalPrice: 1800.0,
        id: "item09",
      },
    ],
    senderAddress: {
      street: "444 Oak Blvd",
      city: "Sunshine City",
      postCode: "86420",
      country: "USA",
    },
    clientAddress: {
      street: "333 Sunrise St",
      city: "Dawnville",
      postCode: "97531",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a14",
  },
  {
    invoiceId: "INV008",
    description: "App development",
    status: "pending",
    paymentDue: "2023-08-20T00:00:00Z",
    paymentTerms: "30 days",
    clientName: "Hank Pym",
    clientEmail: "hank@example.com",
    total: 4500.0,
    items: [
      {
        name: "Mobile app development",
        qty: 1,
        price: 4500.0,
        totalPrice: 4500.0,
        id: "item10",
      },
    ],
    senderAddress: {
      street: "789 Redwood Dr",
      city: "Tree City",
      postCode: "75319",
      country: "USA",
    },
    clientAddress: {
      street: "456 Redwood Dr",
      city: "Leaf Town",
      postCode: "86420",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a16",
  },
  {
    invoiceId: "INV009",
    description: "E-commerce development",
    status: "paid",
    paymentDue: "2023-09-01T00:00:00Z",
    paymentTerms: "60 days",
    clientName: "Ivy Black",
    clientEmail: "ivy@example.com",
    total: 5000.0,
    items: [
      {
        name: "E-commerce website",
        qty: 1,
        price: 5000.0,
        totalPrice: 5000.0,
        id: "item11",
      },
    ],
    senderAddress: {
      street: "123 Evergreen Ln",
      city: "Forest City",
      postCode: "75319",
      country: "USA",
    },
    clientAddress: {
      street: "456 Forest Ln",
      city: "Green Town",
      postCode: "86420",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a18",
  },
  {
    invoiceId: "INV010",
    description: "Cybersecurity audit",
    status: "draft",
    paymentDue: "2023-08-25T00:00:00Z",
    paymentTerms: "30 days",
    clientName: "Jack Ryan",
    clientEmail: "jack@example.com",
    total: 2000.0,
    items: [
      {
        name: "Security audit",
        qty: 1,
        price: 2000.0,
        totalPrice: 2000.0,
        id: "item12",
      },
    ],
    senderAddress: {
      street: "789 Skyway Dr",
      city: "Cloud City",
      postCode: "24680",
      country: "USA",
    },
    clientAddress: {
      street: "456 Blue Sky Ln",
      city: "Sky Town",
      postCode: "75319",
      country: "USA",
    },
    userId: "64b8f3928f8f3a1e4c1b4a20",
  },
];
